Harness: reduce output for skipped tests
This has the practical effect of reducing the number of error like this
that appear on OS X (though the root cause of that problem is still not
known).

  Traceback (most recent call last):
    File "./runTests.py", line 78, in <module>
      h.execute()
    File "/Users/patrick/pythontestharness/lib/pyTestHarness/harness.py", line 178, in execute
      print(pthcolors.WARNING+'[-- Skipping test: ' + test.name + ' --]' +pthcolors.ENDC)
  BlockingIOError: [Errno 35] write could not complete without blocking